version: '3'
services:
  secure-storage-mysql:
    container_name: secure-storage-mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: securestorage
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  secure-storage:
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - secure-storage-mysql